"""将讨论结果导出为 Markdown"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..core.models import Decision, Message, TaskCard, Thread

# 角色 emoji 映射
_ROLE_EMOJI: dict[str, str] = {
    "idea": "💡",
    "architect": "🏗️",
    "coder": "💻",
    "reviewer": "🔍",
    "qa": "🧪",
    "security": "🔒",
    "perf": "⚡",
    "docs": "📝",
    "planner": "📋",
    "moderator": "🎙️",
    "judge": "⚖️",
}

_MODE_LABEL: dict[str, str] = {
    "debate": "Debate → Synthesize",
    "pair_programming": "Pair Programming",
    "red_blue_team": "Red/Blue Team",
    "spec_first": "Spec-first",
    "tdd_loop": "TDD Loop",
}


class MarkdownExporter:
    """将讨论结果导出为 Markdown"""

    @staticmethod
    async def export_thread(
        thread: Thread,
        messages: list[Message],
        decision: Decision | None = None,
        tasks: list[TaskCard] | None = None,
    ) -> str:
        """生成 Markdown 格式的讨论报告"""
        lines: list[str] = []

        # ── 标题 ──
        lines.append(f"# 📋 {thread.topic}")
        lines.append("")

        # ── 元信息 ──
        roles = sorted({m.agent_role.value for m in messages})
        role_tags = ", ".join(
            f"{_ROLE_EMOJI.get(r, '👤')} {r.capitalize()}" for r in roles
        )
        mode_label = _MODE_LABEL.get(thread.mode.value, thread.mode.value)

        lines.append("## ℹ️ Meta")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("| --- | --- |")
        lines.append(f"| **Thread ID** | `{thread.id}` |")
        lines.append(f"| **Created** | {thread.created_at.strftime('%Y-%m-%d %H:%M')} |")
        lines.append(f"| **Mode** | {mode_label} |")
        lines.append(f"| **Rounds** | {thread.current_round} / {thread.max_rounds} |")
        lines.append(f"| **Status** | {thread.status.value} |")
        lines.append(f"| **Participants** | {role_tags} |")
        lines.append("")

        # ── 讨论过程 ──
        lines.append("## 💬 Discussion")
        lines.append("")

        for i, msg in enumerate(messages, 1):
            emoji = _ROLE_EMOJI.get(msg.agent_role.value, "👤")
            role_name = msg.agent_role.value.capitalize()
            lines.append(f"### {i}. {emoji} {role_name} — _{msg.msg_type.value}_")
            lines.append("")
            lines.append(msg.content)
            lines.append("")

            eb = msg.evidence_block
            if eb:
                if eb.claim:
                    lines.append(f"> **💡 Claim:** {eb.claim}")
                    lines.append(">")
                if eb.evidence:
                    lines.append(f"> **📊 Evidence:** {eb.evidence}")
                    lines.append(">")
                if eb.risk:
                    lines.append(f"> **⚠️ Risk:** {eb.risk}")
                    lines.append(">")
                if eb.next_step:
                    lines.append(f"> **➡️ Next Step:** {eb.next_step}")
                lines.append("")

            lines.append("---")
            lines.append("")

        # ── 最终决策 ──
        if decision:
            lines.append("## ⚖️ Decision")
            lines.append("")
            lines.append(f"**Status:** {decision.status.value}")
            lines.append("")
            lines.append(f"**Summary:** {decision.summary}")
            lines.append("")
            if decision.chosen_option:
                lines.append(f"**Chosen Option:** {decision.chosen_option}")
                lines.append("")
            if decision.reasoning:
                lines.append(f"**Reasoning:** {decision.reasoning}")
                lines.append("")

        # ── 任务列表 ──
        if tasks:
            lines.append("## ✅ Tasks")
            lines.append("")
            lines.append("| # | Objective | Assignees | Status |")
            lines.append("| --- | --- | --- | --- |")
            for i, t in enumerate(tasks, 1):
                assignees = ", ".join(r.value.capitalize() for r in t.assignee_roles)
                lines.append(f"| {i} | {t.objective} | {assignees} | {t.status.value} |")
            lines.append("")
            for i, t in enumerate(tasks, 1):
                if t.definition_of_done:
                    lines.append(f"**Task {i} — Definition of Done:** {t.definition_of_done}")
                    lines.append("")

        # ── 页脚 ──
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Agent Company 🏢*")
        lines.append("")

        return "\n".join(lines)
